#!/bin/sh
# this compiles all of the standard java-sourced libraries for GPCP
rm -rf dest
mkdir dest
javac -cp dest -d dest Console.java
javac -cp dest -d dest CPJ.java
javac -cp dest -d dest CPJrts.java
javac -cp dest -d dest XHR.java
javac -cp dest -d dest CPmain.java
javac -cp dest -d dest Error.java
javac -cp dest -d dest GPFiles_FILE.java
javac -cp dest -d dest GPFiles.java
javac -cp dest -d dest GPBinFiles_FILE.java
javac -cp dest -d dest GPBinFiles.java
javac -cp dest -d dest GPTextFiles_FILE.java
javac -cp dest -d dest GPTextFiles.java
javac -cp dest -d dest ProcType.java
javac -cp dest -d dest ProgArgs.java
javac -cp dest -d dest RTS.java
javac -cp dest -d dest StdIn.java
javac -cp dest -d dest VecBase.java
javac -cp dest -d dest VecChr.java
javac -cp dest -d dest VecI32.java
javac -cp dest -d dest VecI64.java
javac -cp dest -d dest VecR32.java
javac -cp dest -d dest VecR64.java
javac -cp dest -d dest VecBase.java
javac -cp dest -d dest VecRef.java
cd dest
jar cvf cprts.jar .
cp cprts.jar ..
cd ..

